import { useEffect, useMemo, useState } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import { Link, Route, Switch, Router as WouterRouter, useLocation } from 'wouter';
import {
  AlarmClock, ArrowLeft, BarChart3, Bell, BookOpen, Brain, CalendarDays, Check,
  CheckCircle2, ChevronLeft, ChevronRight, CircleHelp, Clock3, ExternalLink, GripVertical,
  Home, ListChecks, Menu, MoreHorizontal, Pause, Play, Plus, RotateCcw, Settings2,
  Sparkles, Target, Timer, Trash2, Trophy, X, Zap,
} from 'lucide-react';
import NotFound from '@/pages/not-found';
import { useFirebaseForge } from '@/lib/firebase/hooks';
import type { Store } from '@/lib/firebase/hooks';
import type { Task } from '@/lib/firebase/tasks';
import { AuthLayer } from '@/components/AuthLayer';
import { useAuth } from '@/lib/firebase/auth';
import { auth } from '@/lib/firebase/config';
import { signOut } from 'firebase/auth';

const queryClient = new QueryClient();
function formatMinutes(seconds: number) { const m = Math.floor(seconds / 60); const s = Math.floor(seconds % 60); return `${m}:${String(s).padStart(2, '0')}`; }
function formatLong(seconds: number) { const h = Math.floor(seconds / 3600); const m = Math.floor((seconds % 3600) / 60); return h ? `${h}h ${m}m` : `${m}m`; }
function todayLabel() { return new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date()); }
function todayWeekday() { return new Intl.DateTimeFormat('en-US', { weekday: 'long' }).format(new Date()); }
function iso(daysFromNow: number) { return new Date(Date.now() + daysFromNow * 86400000).toISOString(); }
function sameDay(date: string) { return new Date(date).toDateString() === new Date().toDateString(); }
function nextDay(date: string) { return new Intl.DateTimeFormat('en-US', { weekday: 'short', month: 'short', day: 'numeric' }).format(new Date(date)); }

function AppShell({ children, active }: { children: React.ReactNode; active: string }) {
  const { user } = useAuth();
  const nav = [
    { href: '/', label: 'Overview', icon: Home },
    { href: '/today', label: 'Today', icon: ListChecks },
    { href: '/calendar', label: 'Calendar', icon: CalendarDays },
    { href: '/progress', label: 'Progress', icon: BarChart3 },
    { href: '/revision', label: 'Revision', icon: RotateCcw },
    { href: '/resources', label: 'Resources', icon: BookOpen },
  ];
  return <div className="app-shell">
    <div className="ambient-field" aria-hidden="true"><span className="ambient-orb orb-cyan" /><span className="ambient-orb orb-violet" /><span className="ambient-orb orb-blue" /></div>
    <aside className="side-rail">
      <Link href="/" className="brand" data-testid="link-brand"><span className="brand-mark">F</span><span><span className="brand-name">FocusForge</span><span className="brand-note">steady work, softer days</span></span></Link>
      <div className="nav-label">Workspace</div>
      <nav className="nav-group">{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={`nav-link ${active === href ? 'active' : ''}`} data-testid={`link-nav-${label.toLowerCase()}`}><Icon /><span>{label}</span></Link>)}</nav>
      <div className="rail-footer"><Link href="/settings" className={`nav-link ${active === '/settings' ? 'active' : ''}`} data-testid="link-nav-settings"><Settings2 /><span>Settings</span></Link><div className="profile-row">
      {user?.photoURL ? (
        <img src={user.photoURL} alt="Avatar" className="avatar" style={{ padding: 0, overflow: 'hidden', objectFit: 'cover' }} />
      ) : (
        <span className="avatar">{user?.displayName?.charAt(0).toUpperCase() || 'U'}</span>
      )}
      <span style={{ overflow: 'hidden' }}>
        <div className="profile-name" style={{ whiteSpace: 'nowrap', textOverflow: 'ellipsis', overflow: 'hidden' }}>{user?.displayName || 'User'}</div>
        <div className="profile-sub" style={{ whiteSpace: 'nowrap', textOverflow: 'ellipsis', overflow: 'hidden' }}>{user?.email}</div>
      </span></div></div>
    </aside>
     <div className="main-wrap page-transition" key={active}>
      <header className="topbar"><div className="crumb"><span>FocusForge</span><span>/</span><strong>{active === '/' ? 'Overview' : active.slice(1).replace('-', ' ')}</strong></div><div className="top-actions"><button className="icon-btn" data-testid="button-notifications" aria-label="Notifications"><Bell size={16} /></button><Link className="icon-btn" href="/settings" data-testid="link-settings-top" aria-label="Settings"><Settings2 size={16} /></Link></div></header>
      {children}
    </div>
    <nav className="mobile-nav">{nav.slice(0, 5).map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={active === href ? 'active' : ''} data-testid={`link-mobile-${label.toLowerCase()}`}><Icon /><span>{label}</span></Link>)}</nav>
  </div>;
}

function Layout({ children, active, forge }: { children: React.ReactNode; active: string; forge: ReturnType<typeof useFirebaseForge> }) {
  const task = forge.store.tasks.find(t => t.id === forge.focusId);
  return <><AppShell active={active}>{children}</AppShell>{forge.focusId && task && <FocusModal task={task} forge={forge} />}{forge.toast && <div className="toast-note" data-testid="status-toast">{forge.toast}</div>}</>;
}

function Dashboard({ forge }: { forge: ReturnType<typeof useFirebaseForge> }) {
  const { store, activeSeconds, startTask, setFocusId } = forge;
  const done = store.tasks.filter(t => t.status === 'done').length;
  const studied = store.tasks.reduce((a, t) => a + activeSeconds(t), 0);
  const next = store.tasks.find(t => t.status !== 'done');
  const percent = Math.min(100, Math.round((done / Math.max(1, store.tasks.length)) * 100));
  return <Layout active="/" forge={forge}><main className="content"><div className="header-row"><div><div className="eyebrow">{todayWeekday()} rhythm · {todayLabel()}</div><h1 className="page-title">A clear place to <em>begin.</em></h1><p className="lede">You do not need a perfect day. Just one honest block of attention, then the next.</p></div><Link href="/today" className="btn btn-outline" data-testid="link-open-plan"><ListChecks size={15} /> Open today’s plan</Link></div>
    <div className="dashboard-grid"><section className="card today-hero"><div className="hero-content"><span className="hero-kicker">Your next right thing</span><div className="hero-title">{next ? next.topic : 'You made it through the plan.'}</div><div className="hero-copy">{next ? next.goal : 'Take a breath and notice what you completed today.'}</div><div className="hero-actions">{next && <button className="btn btn-primary" onClick={() => startTask(next.id)} data-testid="button-start-next"><Play size={14} fill="currentColor" /> Start {next.plannedMinutes} min</button>}<Link href="/today" className="btn btn-outline" data-testid="link-see-all-tasks">See all tasks</Link></div></div></section>
      <section className="card card-pad metrics-card"><div className="metrics-head"><div><div className="section-title">Today, in focus</div><div className="section-sub">Progress without the pressure.</div></div><Target size={19} color="hsl(179 34% 34%)" /></div><div className="metric-number" data-testid="text-study-time">{formatLong(studied)}</div><div className="metric-caption">active study time</div><div className="progress-track" style={{ marginTop: 22 }}><div className="progress-fill" style={{ width: `${percent}%` }} /></div><div className="metric-row"><span>{done} of {store.tasks.length} tasks finished</span><span>{percent}%</span></div></section></div>
    <div className="lower-grid"><section className="card card-pad"><div className="toolbar"><div><div className="section-title">Today’s path</div><div className="section-sub">Small steps, kept visible.</div></div><Link href="/today" className="btn btn-quiet" data-testid="link-manage-tasks">Manage <ChevronRight size={14} /></Link></div><div className="task-list">{store.tasks.slice(0, 4).map(task => <TaskRow key={task.id} task={task} seconds={activeSeconds(task)} onStart={() => task.status === 'active' ? setFocusId(task.id) : startTask(task.id)} />)}</div></section>
      <div className="side-stack"><section className="card card-pad"><div className="section-title">A gentle rescue</div><div className="section-sub">For days that got away from you.</div><div className="rescue-copy">You can still keep the thread. Do one 12-minute block on the task that matters most, then stop with a clean slate.</div><button className="btn btn-soft" onClick={() => next && startTask(next.id)} data-testid="button-rescue-plan"><Sparkles size={14} /> Accept rescue plan</button></section>
      <section className="card card-pad"><div className="section-title">This week's return</div><div className="section-sub" style={{ fontSize: '0.7rem', opacity: 0.6 }}>Based on completed tasks per day</div><div className="streak">{Array.from({ length: 7 }, (_, i) => { const day = new Date(); day.setDate(day.getDate() - (6 - i)); const dayTasks = store.tasks.filter(t => t.status === 'done' && t.completedAt && new Date(t.completedAt).toDateString() === day.toDateString()); return { h: Math.min(100, Math.max(dayTasks.length > 0 ? 25 + dayTasks.length * 20 : 4, 4)), label: ['S','M','T','W','T','F','S'][day.getDay()] }; }).map(({ h, label }, i) => <div className="streak-day" key={i}><div className={`streak-bar ${i === 6 ? 'current' : ''}`} style={{ height: `${h}%` }} /><span className="streak-label">{label}</span></div>)}</div><div className="metric-row"><span>Consistency is a practice</span><span>{Array.from({ length: 7 }, (_, i) => { const day = new Date(); day.setDate(day.getDate() - (6 - i)); return store.tasks.some(t => t.status === 'done' && t.completedAt && new Date(t.completedAt).toDateString() === day.toDateString()) ? 1 : 0; }).reduce((a: number, b: number) => a + b, 0)} / 7 days</span></div></section></div></div>
  </main></Layout>;
}

function TaskRow({ task, seconds, onStart, detailed = false }: { task: Task; seconds: number; onStart: () => void; detailed?: boolean }) {
  return <div className="task-row" data-testid={`row-task-${task.id}`}><span className={`task-dot ${task.status === 'done' ? 'done' : task.priority === 'medium' ? 'orange' : ''}`} /><div className="task-main"><div className="task-title">{task.topic}</div><div className="task-meta"><span className="tag">{task.subject}</span><span>{task.status === 'done' ? 'Finished' : task.status === 'active' ? 'In focus' : task.priority === 'high' ? 'Priority' : 'Planned'}</span></div></div><span className="task-time">{formatMinutes(seconds)} / {task.plannedMinutes}:00</span>{!detailed && <button className="btn btn-quiet" onClick={onStart} data-testid={`button-start-task-${task.id}`}>{task.status === 'done' ? <Check size={15} /> : task.status === 'active' ? <Timer size={15} /> : <Play size={15} />}</button>}</div>;
}

function Today({ forge }: { forge: ReturnType<typeof useFirebaseForge> }) {
  const { store, activeSeconds, startTask, finishTask, reorder, setToast } = forge;
  const [addOpen, setAddOpen] = useState(false);
  const [drag, setDrag] = useState<number>();
  return <Layout active="/today" forge={forge}><main className="content"><div className="header-row"><div><div className="eyebrow">Daily plan · {todayWeekday()}</div><h1 className="page-title">Keep the day <em>close.</em></h1><p className="lede">Arrange your attention before the day arranges it for you.</p></div><button className="btn btn-primary" onClick={() => setAddOpen(true)} data-testid="button-add-task"><Plus size={15} /> Add task</button></div>
    <div className="page-layout"><section className="card"><div className="card-pad"><div className="toolbar"><div><div className="section-title">{store.tasks.filter(t => t.status === 'done').length} complete · {store.tasks.length} planned</div><div className="section-sub">Drag to shape your sequence.</div></div><button className="btn btn-outline" onClick={() => setToast('Plan saved locally.')} data-testid="button-save-plan">Save plan</button></div></div><div>{store.tasks.map((task, i) => <div className="plan-row" key={task.id} draggable onDragStart={() => setDrag(i)} onDragOver={e => e.preventDefault()} onDrop={() => { if (drag !== undefined && drag !== i) reorder(drag, i); setDrag(undefined); }} data-testid={`row-planned-task-${task.id}`}><GripVertical size={16} className="drag" /><div className="task-main"><div className="task-title"><span className={`priority ${task.priority === 'low' ? 'low' : ''}`} />{task.topic}</div><div className="task-meta"><span className="tag">{task.subject}</span><span>{task.goal}</span></div></div><div className="row-actions"><span className="task-time">{formatMinutes(activeSeconds(task))}</span>{task.status !== 'done' && <button className="btn btn-quiet" onClick={() => startTask(task.id)} data-testid={`button-focus-${task.id}`}>{task.status === 'active' ? <Timer size={16} /> : <Play size={16} />}</button>}{task.status !== 'done' && <button className="btn btn-quiet" onClick={() => finishTask(task.id)} data-testid={`button-finish-${task.id}`}><CheckCircle2 size={16} /></button>}<button className="btn btn-quiet" onClick={() => forge.deleteTask(task.id)} data-testid={`button-delete-${task.id}`}><Trash2 size={16} /></button></div></div>)}</div></section>
      <aside className="side-stack"><section className="card card-pad"><div className="section-title">Plan notes</div><div className="section-sub">A little context for future-you.</div><div className="mini-list">{store.tasks.slice(0, 3).map(t => <div className="mini-line" key={t.id}><span>{t.subject}</span><span>{t.plannedMinutes}m</span></div>)}</div></section><section className="card card-pad rescue-card"><div className="rescue-mark"><Zap size={16} /></div><div className="section-title" style={{ marginTop: 13 }}>If focus feels far away</div><div className="rescue-copy">Start with 12 minutes. The goal is contact, not completion.</div><button className="btn btn-soft" onClick={() => { const t = store.tasks.find(x => x.status !== 'done'); if (t) startTask(t.id); }} data-testid="button-start-rescue">Start small block</button></section></aside></div>
  </main>{addOpen && <AddTaskModal onClose={() => setAddOpen(false)} onAdd={data => { forge.addTask(data); setAddOpen(false); }} />}</Layout>;
}

function AddTaskModal({ onClose, onAdd }: { onClose: () => void; onAdd: (data: Omit<Task, 'id' | 'actualActiveSeconds' | 'status' | 'createdAt'>) => void }) {
  const [subject, setSubject] = useState('Python'); const [topic, setTopic] = useState(''); const [minutes, setMinutes] = useState('30'); const [priority, setPriority] = useState<Task['priority']>('medium'); const [goal, setGoal] = useState('');
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><div className="modal"><div className="modal-head"><div><h2 className="modal-title">Add to today</h2><div className="section-sub">Give the next block a name and a shape.</div></div><button className="icon-btn" onClick={onClose} data-testid="button-close-add-task"><X size={16} /></button></div><div className="modal-body"><div className="form-grid"><div className="field"><label>Subject</label><select value={subject} onChange={e => setSubject(e.target.value)} data-testid="select-task-subject"><option>Python</option><option>DSA</option><option>Java</option><option>SQL</option><option>Other</option></select></div><div className="field"><label>Planned minutes</label><input type="number" min="5" max="180" value={minutes} onChange={e => setMinutes(e.target.value)} data-testid="input-task-minutes" /></div><div className="field full"><label>Topic</label><input autoFocus placeholder="e.g. React state patterns" value={topic} onChange={e => setTopic(e.target.value)} data-testid="input-task-topic" /></div><div className="field full"><label>What would done look like?</label><textarea placeholder="A small, concrete finish line" value={goal} onChange={e => setGoal(e.target.value)} data-testid="input-task-goal" /></div><div className="field"><label>Priority</label><select value={priority} onChange={e => setPriority(e.target.value as Task['priority'])} data-testid="select-task-priority"><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div></div><div className="modal-actions"><button className="btn btn-outline" onClick={onClose} data-testid="button-cancel-add-task">Not now</button><button className="btn btn-primary" disabled={!topic.trim()} onClick={() => onAdd({ subject, topic: topic.trim(), plannedMinutes: Number(minutes) || 30, priority, goal: goal.trim() || 'Make a little progress.', deadline: new Date().toISOString(), resources: [], notes: '' })} data-testid="button-confirm-add-task"><Plus size={14} /> Add task</button></div></div></div></div>;
}

function FocusModal({ task, forge }: { task: Task; forge: ReturnType<typeof useFirebaseForge> }) {
  const { store, activeSeconds, pauseActive, resumeTask, finishTask, setFocusId, now, setToast } = forge;
  const [losing, setLosing] = useState(false); const [pauseReason, setPauseReason] = useState(false); const [breakMode, setBreakMode] = useState(false); const [breakLeft, setBreakLeft] = useState(store.timer.breakMinutes * 60);
  const isRunning = store.activeTaskId === task.id;
  const seconds = activeSeconds(task);
  useEffect(() => { if (!breakMode) return; const id = window.setInterval(() => setBreakLeft(v => Math.max(0, v - 1)), 1000); return () => window.clearInterval(id); }, [breakMode]);
  const close = () => setFocusId(undefined);
  return <div className="modal-backdrop"><div className="modal focus-modal">{breakMode ? <><div className="focus-top"><span className="focus-label">A quiet break</span><button className="icon-btn" onClick={close} data-testid="button-close-break"><X size={16} /></button></div><div className="modal-body"><div className="focus-task">Let your attention reset.</div><div className="section-sub">Step away from the screen. Your work is safe here.</div><div className="timer">{formatMinutes(breakLeft)}<small>break remaining</small></div><div className="focus-controls"><button className="btn btn-primary" onClick={() => { setBreakMode(false); setToast('Back to your plan when you are ready.'); }} data-testid="button-end-break">Return to task</button></div></div></> : <><div className="focus-top"><span className="focus-label"><Timer size={12} /> Focus session</span><button className="icon-btn" onClick={close} data-testid="button-close-focus"><X size={16} /></button></div><div className="modal-body"><div className="focus-task">{task.topic}</div><div className="focus-subject">{task.subject} · {task.goal}</div><div className="timer" data-testid="text-focus-timer">{formatMinutes(seconds)}<small>of {task.plannedMinutes}:00 planned</small></div><div className="focus-controls">{isRunning ? <button className="btn btn-soft" onClick={() => setPauseReason(true)} data-testid="button-pause-focus"><Pause size={14} /> Pause</button> : <button className="btn btn-primary" onClick={() => resumeTask(task.id)} data-testid="button-resume-focus"><Play size={14} fill="currentColor" /> Resume</button>}<button className="btn btn-primary" onClick={() => finishTask(task.id)} data-testid="button-finish-focus"><Check size={14} /> Finish</button><button className="btn btn-outline" onClick={() => { setBreakLeft(store.timer.breakMinutes * 60); setBreakMode(true); if (isRunning) pauseActive('break'); }} data-testid="button-start-break"><Clock3 size={14} /> Break</button></div><button className="btn btn-quiet" onClick={() => setLosing(true)} style={{ marginTop: 18 }} data-testid="button-losing-focus"><CircleHelp size={14} /> I’m losing focus</button><div className="focus-tip">One block is enough. You can pause without losing the work you already did.</div></div>{(losing || pauseReason) && <ReasonModal losing={losing} onClose={() => { setLosing(false); setPauseReason(false); }} onChoose={reason => { if (isRunning) pauseActive(reason); setLosing(false); setPauseReason(false); setToast(reason === 'break' ? 'Paused. Take the space you need.' : 'Paused and logged. You can return when ready.'); }} />}</>}</div></div>;
}

function ReasonModal({ losing, onClose, onChoose }: { losing: boolean; onClose: () => void; onChoose: (reason: string) => void }) {
  const reasons = losing ? ['My mind is wandering', 'I need a clearer next step', 'Something interrupted me'] : ['Quick reset', 'Need to step away', 'Done for now'];
  return <div className="modal-backdrop" style={{ zIndex: 60 }}><div className="modal" style={{ width: 'min(100%, 420px)' }}><div className="modal-head"><div><h2 className="modal-title">{losing ? 'Name the snag' : 'Why are you pausing?'}</h2><div className="section-sub">{losing ? 'No judgment. Naming it can make returning easier.' : 'A pause is part of a sustainable session.'}</div></div><button className="icon-btn" onClick={onClose} data-testid="button-close-reason"><X size={16} /></button></div><div className="modal-body">{reasons.map(reason => <button key={reason} className="btn btn-outline" style={{ width: '100%', marginBottom: 8, justifyContent: 'flex-start' }} onClick={() => onChoose(reason)} data-testid={`button-reason-${reason.toLowerCase().replaceAll(' ', '-')}`}>{reason}</button>)}</div></div></div>;
}

function CalendarPage({ forge }: { forge: ReturnType<typeof useFirebaseForge> }) {
  const [month, setMonth] = useState(new Date()); const days = useMemo(() => { const start = new Date(month.getFullYear(), month.getMonth(), 1); const first = (start.getDay() + 6) % 7; const total = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); const cells: { date: Date; current: boolean }[] = []; for (let i = first - 1; i >= 0; i--) cells.push({ date: new Date(month.getFullYear(), month.getMonth(), -i), current: false }); for (let d = 1; d <= total; d++) cells.push({ date: new Date(month.getFullYear(), month.getMonth(), d), current: true }); while (cells.length < 35) cells.push({ date: new Date(month.getFullYear(), month.getMonth() + 1, cells.length - total - first + 1), current: false }); return cells; }, [month]);
  return <Layout active="/calendar" forge={forge}><main className="content"><div className="header-row"><div><div className="eyebrow">Make room for what matters</div><h1 className="page-title">A month with <em>breathing room.</em></h1><p className="lede">See your study rhythm beside the rest of life. The plan is allowed to move.</p></div><div className="toolbar-controls"><button className="icon-btn" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} data-testid="button-calendar-prev"><ChevronLeft size={16} /></button><button className="icon-btn" onClick={() => setMonth(new Date())} data-testid="button-calendar-today"><Target size={15} /></button><button className="icon-btn" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} data-testid="button-calendar-next"><ChevronRight size={16} /></button></div></div><section className="card card-pad"><div className="calendar-head"><div className="calendar-title">{new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric' }).format(month)}</div><div className="section-sub"><span style={{ color: 'hsl(var(--primary))' }}>● Study</span> &nbsp; <span style={{ color: 'hsl(25 48% 35%)' }}>● Other</span></div></div><div className="calendar-scroll"><div className="calendar-grid">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d => <div className="cal-day-name" key={d}>{d}</div>)}{days.map(({ date, current }, i) => { const isToday = date.toDateString() === new Date().toDateString(); const tasks = current ? forge.store.tasks.filter(t => new Date(t.createdAt).toDateString() === date.toDateString()) : []; return <div className={`cal-cell ${current ? '' : 'muted-day'}`} key={`${date.toISOString()}-${i}`}><span className={`cal-date ${isToday ? 'today' : ''}`}>{date.getDate()}</span>{tasks.map(t => <div className="event-pill" key={t.id}>{t.subject} · {t.plannedMinutes}m</div>)}</div>; })}</div></div></section></main></Layout>;
}

function Progress({ forge }: { forge: ReturnType<typeof useFirebaseForge> }) {
  const daily = useMemo(() => Array.from({ length: 7 }, (_, index) => {
    const day = new Date(); day.setHours(0, 0, 0, 0); day.setDate(day.getDate() - (6 - index));
    const next = new Date(day); next.setDate(day.getDate() + 1);
    return Math.round(forge.store.events.reduce((sum, event) => {
      const started = new Date(event.startedAt).getTime();
      const ended = event.endedAt ? new Date(event.endedAt).getTime() : (forge.store.activeTaskId === event.taskId ? Date.now() : started);
      return started >= day.getTime() && started < next.getTime() ? sum + Math.max(0, ended - started) / 60000 : sum;
    }, 0) + (index === 6 ? forge.store.tasks.reduce((sum, task) => sum + forge.activeSeconds(task) / 60, 0) : 0));
  }), [forge.store, forge.now]);
  const total = daily.reduce((a, b) => a + b, 0); const sessions = forge.store.events.length; const completed = forge.store.tasks.filter(t => t.status === 'done').length;
  return <Layout active="/progress" forge={forge}><main className="content"><div className="header-row"><div><div className="eyebrow">Look back kindly</div><h1 className="page-title">Progress you can <em>trust.</em></h1><p className="lede">A record of returning, not a scoreboard. Notice what is helping.</p></div><div className="tag">Last 7 days</div></div><div className="analytics-grid"><div className="card stat-card"><div className="eyebrow">Active time</div><div className="stat-value" data-testid="text-weekly-time">{formatLong(total * 60)}</div><div className="stat-label">across this week</div></div><div className="card stat-card"><div className="eyebrow">Study blocks</div><div className="stat-value">{sessions}</div><div className="stat-label">with room to pause</div></div><div className="card stat-card"><div className="eyebrow">Finished</div><div className="stat-value">{completed}</div><div className="stat-label">tasks moved forward</div></div></div><div className="page-layout"><section className="card"><div className="card-pad"><div className="section-title">Minutes in focus</div><div className="section-sub">Your effort by day, calculated from active blocks.</div></div><div className="chart">{daily.map((value, i) => <div className="chart-col" key={i}><div className="chart-bar-wrap"><div className={`chart-bar ${i === 6 ? 'highlight' : ''}`} style={{ height: `${Math.max(8, Math.min(100, value))}%` }} /></div><div className="chart-label">{['M','T','W','T','F','S','S'][i]}</div></div>)}</div></section><section className="card card-pad"><div className="section-title">What your week says</div><div className="insight"><strong>Short starts are working.</strong><br />Your most consistent days begin with a block under 30 minutes. Keep that doorway open.</div><div className="insight" style={{ borderColor: 'hsl(var(--primary))', background: 'hsl(var(--accent) / .35)' }}><strong>Your pace is sustainable.</strong><br />Pauses are part of the pattern, not proof that the pattern failed.</div></section></div></main></Layout>;
}

function Revision({ forge }: { forge: ReturnType<typeof useFirebaseForge> }) {
  const [tab, setTab] = useState<'due' | 'upcoming'>('due'); const visible = forge.store.revisions.filter(r => r.status === tab);
  const review = (id: string) => { const rev = forge.store.revisions.find(r => r.id === id); if (rev) forge.reviewRevision(id, rev.intervalDays); };
  return <Layout active="/revision" forge={forge}><main className="content"><div className="header-row"><div><div className="eyebrow">Keep knowledge warm</div><h1 className="page-title">The <em>revision</em> queue.</h1><p className="lede">Completed topics return gently, just before they go cold.</p></div><div className="segmented"><button className={tab === 'due' ? 'active' : ''} onClick={() => setTab('due')} data-testid="button-revision-due">Due now</button><button className={tab === 'upcoming' ? 'active' : ''} onClick={() => setTab('upcoming')} data-testid="button-revision-upcoming">Upcoming</button></div></div><div className="page-layout"><section className="card card-pad"><div className="section-title">{tab === 'due' ? 'A few things to revisit' : 'Already on the horizon'}</div><div className="section-sub">Keep each review light: retrieve, check, move on.</div><div style={{ marginTop: 14 }}>{visible.length ? visible.map(item => <div className="revision-row" key={item.id}><div className="revision-icon"><Brain size={16} /></div><div className="revision-main"><div className="revision-topic">{item.topic}</div><div className="revision-sub">{item.subject} · {item.intervalDays}-day interval</div></div><span className="due">{tab === 'due' ? 'Due today' : nextDay(item.dueDate)}</span>{tab === 'due' && <button className="btn btn-soft" onClick={() => review(item.id)} data-testid={`button-review-${item.id}`}><Check size={14} /> Review</button>}</div>) : <div className="empty"><CheckCircle2 size={28} /><strong>Queue is clear.</strong><span>Nothing needs your attention right now.</span></div>}</div></section><section className="card card-pad rescue-card"><div className="rescue-mark"><BookOpen size={16} /></div><div className="section-title" style={{ marginTop: 13 }}>Review, don’t relearn</div><div className="rescue-copy">Try to recall the idea before opening your notes. A little friction makes the memory stronger.</div></section></div></main></Layout>;
}

function Resources({ forge }: { forge: ReturnType<typeof useFirebaseForge> }) {
  const [query, setQuery] = useState('');
  const resources = forge.store.tasks.flatMap(t => t.resources.map((resource, i) => ({ id: `${t.id}-${i}`, resource, task: t }))).filter(r => `${r.resource} ${r.task.topic}`.toLowerCase().includes(query.toLowerCase()));
  return <Layout active="/resources" forge={forge}><main className="content"><div className="header-row"><div><div className="eyebrow">Your study shelf</div><h1 className="page-title">Resources that <em>stay nearby.</em></h1><p className="lede">Keep the links and notes attached to the work they support.</p></div><div className="field" style={{ minWidth: 220 }}><label htmlFor="resource-search">Find a resource</label><input id="resource-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search topics or links" data-testid="input-resource-search" /></div></div><div className="page-layout"><section className="card card-pad"><div className="section-title">Saved resources</div><div className="section-sub">{resources.length} resources across your plan</div><div style={{ marginTop: 14 }}>{resources.length ? resources.map(({ id, resource, task }) => <div className="resource-row" key={id}><div className="revision-icon"><ExternalLink size={15} /></div><div className="resource-main"><div className="resource-topic">{resource}</div><div className="resource-sub">{task.subject} · {task.topic}</div></div><span className="resource-type">reference</span></div>) : <div className="empty"><BookOpen size={28} /><strong>No matching resources.</strong><span>Try a subject or topic.</span></div>}</div></section><section className="card card-pad"><div className="section-title">Notes in context</div><div className="section-sub">Notes travel with each task.</div><div className="mini-list">{forge.store.tasks.filter(t => t.notes).map(t => <div className="mini-line" key={t.id}><span>{t.topic}</span><span>{t.notes}</span></div>)}</div></section></div></main></Layout>;
}

function Settings({ forge }: { forge: ReturnType<typeof useFirebaseForge> }) {
  const { timer } = forge.store; const update = (changes: Partial<Store['timer']>) => forge.setStore(s => ({ ...s, timer: { ...s.timer, ...changes } }));
  const handleLogout = () => { signOut(auth); };
  return <Layout active="/settings" forge={forge}><main className="content"><div className="header-row"><div><div className="eyebrow">Make it yours</div><h1 className="page-title">Settings for <em>steady work.</em></h1><p className="lede">Tune the workspace so it asks less of you.</p></div></div><div className="page-layout"><section className="card card-pad"><div className="section-title">Timer & rhythm</div><div className="section-sub">Your defaults for a focus block.</div><div className="settings-list" style={{ marginTop: 18 }}><div className="setting-row"><div><div className="setting-name">Focus length</div><div className="setting-desc">How long a new block begins.</div></div><div className="field" style={{ width: 105 }}><select value={timer.focusMinutes} onChange={e => update({ focusMinutes: Number(e.target.value) })} data-testid="select-focus-length"><option value="25">25 min</option><option value="45">45 min</option><option value="60">60 min</option></select></div></div><div className="setting-row"><div><div className="setting-name">Break length</div><div className="setting-desc">A real pause, not a punishment.</div></div><div className="field" style={{ width: 105 }}><select value={timer.breakMinutes} onChange={e => update({ breakMinutes: Number(e.target.value) })} data-testid="select-break-length"><option value="5">5 min</option><option value="10">10 min</option><option value="15">15 min</option></select></div></div><SettingToggle title="Suggest a break after focus" desc="Offer a break when you finish a planned block." on={timer.autoBreak} set={() => update({ autoBreak: !timer.autoBreak })} testId="toggle-auto-break" /><SettingToggle title="Quiet reminders" desc="A small nudge when a planned session is waiting." on={timer.notifications} set={() => update({ notifications: !timer.notifications })} testId="toggle-notifications" /></div></section><section className="card card-pad"><div className="section-title">Account</div><div className="section-sub">Manage your active session.</div><button className="btn btn-outline" style={{ marginTop: 18 }} onClick={handleLogout} data-testid="button-logout">Sign Out</button></section></div></main></Layout>;
}
function SettingToggle({ title, desc, on, set, testId }: { title: string; desc: string; on: boolean; set: () => void; testId: string }) { return <div className="setting-row"><div><div className="setting-name">{title}</div><div className="setting-desc">{desc}</div></div><button className={`toggle ${on ? 'on' : ''}`} onClick={set} data-testid={testId} aria-label={title}><span /></button></div>; }

function RoutedErrorBoundary({ children }: { children: React.ReactNode }) { const [location] = useLocation(); return <ErrorBoundary resetKey={location}>{children}</ErrorBoundary>; }
function Router() {
  const forge = useFirebaseForge();
  return <RoutedErrorBoundary><Switch><Route path="/"><Dashboard forge={forge} /></Route><Route path="/today"><Today forge={forge} /></Route><Route path="/calendar"><CalendarPage forge={forge} /></Route><Route path="/progress"><Progress forge={forge} /></Route><Route path="/revision"><Revision forge={forge} /></Route><Route path="/resources"><Resources forge={forge} /></Route><Route path="/settings"><Settings forge={forge} /></Route><Route component={NotFound} /></Switch></RoutedErrorBoundary>;
}
function App() { return <QueryClientProvider client={queryClient}><TooltipProvider><AuthLayer><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}><Router /></WouterRouter></AuthLayer><Toaster /></TooltipProvider></QueryClientProvider>; }
export default App;