import { Task } from './tasks';

/**
 * Creates an event in the user's primary Google Calendar.
 * Requires the `google_calendar_token` in localStorage, populated during sign-in.
 */
export async function syncTaskToCalendar(task: Omit<Task, 'id' | 'actualActiveSeconds' | 'status' | 'createdAt'>): Promise<boolean | 'token_expired'> {
  const token = localStorage.getItem('google_calendar_token');
  if (!token) {
    console.warn("No Google Calendar token found. User might need to sign in again to grant Calendar permissions.");
    return false;
  }

  const startDate = new Date();
  const endDate = new Date(startDate.getTime() + task.plannedMinutes * 60000);

  const event = {
    summary: `Study: ${task.topic}`,
    description: `Subject: ${task.subject}\nGoal: ${task.goal}\n\nGenerated by FocusForge.`,
    start: {
      dateTime: startDate.toISOString(),
    },
    end: {
      dateTime: endDate.toISOString(),
    },
    reminders: {
      useDefault: false,
      overrides: [
        { method: 'popup', minutes: 10 },
      ],
    },
  };

  try {
    const response = await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(event),
    });

    if (!response.ok) {
      if (response.status === 401 || response.status === 403) {
        // M1: Token expired — clear stale token and signal to UI
        localStorage.removeItem('google_calendar_token');
        console.warn("Google Calendar token expired. Cleared stale token.");
        return 'token_expired';
      }
      throw new Error(`Calendar API Error: ${response.statusText}`);
    }

    return true;
  } catch (error) {
    console.error("Failed to sync to Google Calendar:", error);
    return false;
  }
}
